### ISSUE TITLE
The "path" argument must be of type string. Received type undefined 

### ISSUE THREAD

**Issue by syed-haroon** [gaven/nuxt-svg-sprite-module#1]
I am getting this error when I did just as mentioned:

>  FATAL  The "path" argument must be of type string. Received type undefined                                                                    21:33:09
> 
>   at assertPath (path.js:39:11)
>   at join (path.js:1155:7)
>   at ModuleContainer.module.exports (node_modules/nuxt-svg-sprite-module/index.js:87:23)
>   at Promise (node_modules/@nuxt/core/dist/core.js:172:30)
>   at new Promise (<anonymous>)
>   at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:170:12)
>   at promise.then (node_modules/@nuxt/common/dist/common.js:1321:43)
>   at process._tickCallback (internal/process/next_tick.js:68:7)
>   at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>   at startup (internal/bootstrap/node.js:279:19)
> 
> 
>    ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
>    │                                                                                                           │
>    │   ✖ Nuxt Fatal Error                                                                                      │
>    │                                                                                                           │
>    │   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined   │
>    │                                                                                                           │
>    ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-living@1.0.0 dev: `nuxt`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-living@1.0.0 dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/syedharoon/.npm/_logs/2018-12-24T16_03_09_767Z-debug.log

**Comment by gaven** [comment]
@syed-haroon Could you post your `nuxt.config.js`?

**Comment by syed-haroon** [comment]
@gaven sorry! I had to change the config as `nuxt-svg-sprite-module` did not work for me, and ended up with `vue-svg-loader` but to give you an idea , it was almost like this:

```

const pkg = require('./package');

module.exports = {
  mode: 'universal',

  /*
  ** Headers of the page
  */
  head: {
    title: pkg.name,
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: pkg.description },
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
    ],
  },

  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },

  /*
  ** Global CSS
  */
  css: [
  ],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    '~plugins/icons',
    { src: '~plugins/vue-carousel', ssr: false },
  ],

  /*
  ** Nuxt.js modules
  */
  modules: [
  ],

  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/,
        });
      }

      // Config vue-svg-loader
      const svgRule = config.module.rules.find(rule => rule.test.test('.svg'));
      svgRule.test = /\.(png|jpe?g|gif|webp)$/;

      config.module.rules.push({
        test: /\.svg$/,
        loader: 'vue-svg-loader',
        options: {
          // optional [svgo](https://github.com/svg/svgo) options
          svgo: {
            plugins: [
              { removeDoctype: true },
              { removeComments: true },
              { removeViewBox: false },
              { removeDimensions: true },
              { convertColors: { currentColor: true } },
            ],
          },
        },
      });
    },
  },
};

```

**Comment by coltoneakins** [comment]
I am also seeing this issue. I just followed the steps in the README. I installed the module, adjusted my **nuxt.config.js**, brought down the server, brought up etc.

Nuxt version is v2.3.4.

Here is my full **nuxt.config.js**:


```
const pkg = require('./package')

module.exports = {
  mode: 'spa',

  /*
  ** Headers of the page
  */
  head: {
    title: "Colton Eakins // Modern Front-End Developer // Portfolio and Blog",
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: pkg.description }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#ff0000' },

  /*
  ** Global CSS
  */
  css:[
	  '@/assets/main.scss'
  ],

  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
  ],

  /*
  ** Nuxt.js modules
  */
  modules: [
    // Doc:https://github.com/nuxt-community/modules/tree/master/packages/bulma
    //'@nuxtjs/bulma'
    // Instead, Bulma is compiled in from main.scss above in the Global CSS sectio
    
    'nuxt-svg-sprite-module', {
	directory: '@/assets/icons',
	options: {}
    }
  ],

  /*
  ** Build configuration
  */
  build: {
    postcss: {
      preset: {
        features: {
          customProperties: false
        }
      }
    },
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
}

```

As you can see, it is a pretty basic configuration. Nothing special going on here.

**Comment by gaven** [comment]
@coltoneakins Try removing `@/` before `asset`.

**Comment by coltoneakins** [comment]
I repeated the above steps with all the following:

```
    'nuxt-svg-sprite-module', {
	directory: 'assets/icons',
	options: {}
    }
```
and again with
```
    'nuxt-svg-sprite-module', {
	directory: '/assets/icons',
	options: {}
    }
```
and again with
```
    'nuxt-svg-sprite-module', {
	directory: '~/assets/icons',
	options: {}
    }
```
and again with (just for kicks...)
```
    'nuxt-svg-sprite-module', {
	path: 'assets/icons',
	options: {}
    }
```
All yielded the same error output. I brought back up and down the server each time. The directory also *does* exist. Error persists.

**Comment by coltoneakins** [comment]
Not that it would really matter but I also tried specifying the **options**, removing the trailing **,** comma after the **directory** property, etc. All failed.

**Comment by gaven** [comment]
@coltoneakins Are there any svgs in the directory you specified?

**Comment by coltoneakins** [comment]
I just tried is again. 

Case 1: I tried throwing in an SVG sprite sheet into the **assets/icons** directory. Failed with same error mentioned above.

Case 2: I tried throwing in a bunch of random SVG files into the **assets/icons** directory. Failed with same error mentioned above.


So yes, I have tried with SVG files in the assets/icons directory.

**Comment by gaven** [comment]
@coltoneakins You know what. The read me is off. You need to specify the module as an array. `[nuxt-svg-sprite-module, {}]`

**Comment by gaven** [comment]
I’ve updated the readme with the correct configuration.
